export const INCREMENT_STEPS = 'INCREMENT_STEPS';
export const RESET_STEPS = 'RESET_STEPS';
export const SET_SELECTED_WISDOM = 'SET_SELECTED_WISDOM';
export const SET_ISLOADING = 'SET_ISLOADING';
export const RESET_REDIRECT = 'RESET_REDIRECT';
export const GET_HOME_MESSAGES = 'GET_HOME_MESSAGES';
export const SET_FIRST_WISDOM = 'SET_FIRST_WISDOM';
export const FETCH_WISDOMS = 'FETCH_WISDOMS';
